[book]
#  This book is called
title = "Command Line Applications in Rust"
# ...but friends call it "Clair"
authors = ["The Rust CLI Working Group"]
multilingual = false
language = "ko"
src = "src"

[output.html]
curly-quotes = true
additional-css = ["src/special-content.css"]
git-repository-url = "https://github.com/parksb/rust-cli-book-ko-kr"
site-url = "/book/"

# Linkcheck doesn't find images/SVG so it's not enabled for now
# [output.linkcheck]
